# This is a basic workflow to help you get started with Actions

name: Action to integarte browserstack with GitHub actions

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
     mavenProfile:
       description: "Provide the maven profile to be executed"
       required: true
       default: TestSample




# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '11'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: mvn clean install -PSmokeTest
        

    
